### ISSUE TITLE
Character model render breaks when chest is scanned by thaumometer

### ISSUE THREAD

**Issue by itanshi** [AnimeniacYuuto/EnhancedInventories#11]
http://youtu.be/uUfVuEedxOw

This might only be with TiCon metal chests, but more eh scanning is needed.

**Comment by AnimeniacYuuto** [comment]
Noticed you were using the Regrowth mod pack and this issue appears to be the result of a known issue with Witching Gadgets continuously looping through nugget transmutation recipes. This should be fixed by disabling the "Enable transmutations" option in the Witching Gadgets config.

Sorry I cannot provide a better solution at this time

**Comment by thephoenixlodge** [comment]
Aha! Thanks. I'll fix this for Regrowth 0.7.3
