### ISSUE TITLE
Custom Frames.

### ISSUE THREAD

**Issue by Fortist** [AnimeniacYuuto/EnhancedInventories#38]
Im trying to add various ingots from various mods as frame types, but it seems like they arnt sticking.
Here is a single one, the rest are modeled after this one.

"Thaumium":{
		"name":"frame.ore.thaumium",
		"ColorRed":118,
		"ColorGreen":34,
		"ColorBlue":118,
		"FrameType":0,
		"tier":4,
		"materials":"ingotThaumium"
	},

Am I missing something?

**Comment by Fortist** [comment]
Actually, fiddling around with the file, and something took.
However, I assume the "name" line can just straight up be a name instead of what I wrote there.
Ergo "Thaumium Frame"

**Comment by AnimeniacYuuto** [comment]
Yes you should be able to put the name as what ever you want, the only limitation right now is that the names must be unique, otherwise some will overwrite others, this was an oversight on my part and i apologize for the inconvenience it may cause.

As for the format, in the future it might be a good idea to look at the post init phase of the forge log as it will give details on whats going wrong (or at least it "should" >.>  though should doesn't always mean does).

Any how glad you got it working, let me know if you need any more help
